
package com.opentext.livelink.service.core;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Authentication", targetNamespace = "urn:Core.service.livelink.opentext.com", wsdlLocation = "http://sd1kappuy11:8080/les-services/services/Authentication?wsdl")
public class Authentication_Service
    extends Service
{

    private final static URL AUTHENTICATION_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATION_EXCEPTION;
    private final static QName AUTHENTICATION_QNAME = new QName("urn:Core.service.livelink.opentext.com", "Authentication");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sd1kappuy11:8080/les-services/services/Authentication?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATION_WSDL_LOCATION = url;
        AUTHENTICATION_EXCEPTION = e;
    }

    public Authentication_Service() {
        super(__getWsdlLocation(), AUTHENTICATION_QNAME);
    }

    public Authentication_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATION_QNAME, features);
    }

    public Authentication_Service(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATION_QNAME);
    }

    public Authentication_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATION_QNAME, features);
    }

    public Authentication_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Authentication_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Authentication
     */
    @WebEndpoint(name = "BasicHttpBinding_Authentication")
    public Authentication getBasicHttpBindingAuthentication() {
        return super.getPort(new QName("urn:Core.service.livelink.opentext.com", "BasicHttpBinding_Authentication"), Authentication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authentication
     */
    @WebEndpoint(name = "BasicHttpBinding_Authentication")
    public Authentication getBasicHttpBindingAuthentication(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Core.service.livelink.opentext.com", "BasicHttpBinding_Authentication"), Authentication.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATION_EXCEPTION!= null) {
            throw AUTHENTICATION_EXCEPTION;
        }
        return AUTHENTICATION_WSDL_LOCATION;
    }

}
