
package com.opentext.livelink.service.core;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContentService", targetNamespace = "urn:Core.service.livelink.opentext.com", wsdlLocation = "http://sd1kappuy11:8080/les-services/services/ContentService?wsdl")
public class ContentService_Service
    extends Service
{

    private final static URL CONTENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTENTSERVICE_EXCEPTION;
    private final static QName CONTENTSERVICE_QNAME = new QName("urn:Core.service.livelink.opentext.com", "ContentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sd1kappuy11:8080/les-services/services/ContentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTENTSERVICE_WSDL_LOCATION = url;
        CONTENTSERVICE_EXCEPTION = e;
    }

    public ContentService_Service() {
        super(__getWsdlLocation(), CONTENTSERVICE_QNAME);
    }

    public ContentService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTENTSERVICE_QNAME, features);
    }

    public ContentService_Service(URL wsdlLocation) {
        super(wsdlLocation, CONTENTSERVICE_QNAME);
    }

    public ContentService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTENTSERVICE_QNAME, features);
    }

    public ContentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContentService
     */
    @WebEndpoint(name = "BasicHttpBinding_ContentService")
    public ContentService getBasicHttpBindingContentService() {
        return super.getPort(new QName("urn:Core.service.livelink.opentext.com", "BasicHttpBinding_ContentService"), ContentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContentService
     */
    @WebEndpoint(name = "BasicHttpBinding_ContentService")
    public ContentService getBasicHttpBindingContentService(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Core.service.livelink.opentext.com", "BasicHttpBinding_ContentService"), ContentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTENTSERVICE_EXCEPTION!= null) {
            throw CONTENTSERVICE_EXCEPTION;
        }
        return CONTENTSERVICE_WSDL_LOCATION;
    }

}
