
package com.opentext.livelink.service.core;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContentService", targetNamespace = "urn:Core.service.livelink.opentext.com")
@XmlSeeAlso({
    com.opentext.ecm.api.ObjectFactory.class,
    com.opentext.livelink.service.core.ObjectFactory.class
})
public interface ContentService {


    /**
     * 
     * @param contents
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadContent", action = "urn:Core.service.livelink.opentext.com/UploadContent")
    @WebResult(name = "UploadContentResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    @RequestWrapper(localName = "UploadContent", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.UploadContent")
    @ResponseWrapper(localName = "UploadContentResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.UploadContentResponse")
    public String uploadContent(
        @WebParam(name = "contents", targetNamespace = "urn:Core.service.livelink.opentext.com")
        DataHandler contents);

    /**
     * 
     * @param contextID
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod(operationName = "DownloadContent", action = "urn:Core.service.livelink.opentext.com/DownloadContent")
    @WebResult(name = "DownloadContentResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    @RequestWrapper(localName = "DownloadContent", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.DownloadContent")
    @ResponseWrapper(localName = "DownloadContentResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.DownloadContentResponse")
    public DataHandler downloadContent(
        @WebParam(name = "contextID", targetNamespace = "urn:Core.service.livelink.opentext.com")
        String contextID);

}
