
package com.opentext.livelink.service.docman;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentManagement", targetNamespace = "urn:DocMan.service.livelink.opentext.com", wsdlLocation = "http://sd1kappuy11:8080/les-services/services/DocumentManagement?wsdl")
public class DocumentManagement_Service
    extends Service
{

    private final static URL DOCUMENTMANAGEMENT_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTMANAGEMENT_EXCEPTION;
    private final static QName DOCUMENTMANAGEMENT_QNAME = new QName("urn:DocMan.service.livelink.opentext.com", "DocumentManagement");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sd1kappuy11:8080/les-services/services/DocumentManagement?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCUMENTMANAGEMENT_WSDL_LOCATION = url;
        DOCUMENTMANAGEMENT_EXCEPTION = e;
    }

    public DocumentManagement_Service() {
        super(__getWsdlLocation(), DOCUMENTMANAGEMENT_QNAME);
    }

    public DocumentManagement_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTMANAGEMENT_QNAME, features);
    }

    public DocumentManagement_Service(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTMANAGEMENT_QNAME);
    }

    public DocumentManagement_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTMANAGEMENT_QNAME, features);
    }

    public DocumentManagement_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentManagement_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_DocumentManagement")
    public DocumentManagement getBasicHttpBindingDocumentManagement() {
        return super.getPort(new QName("urn:DocMan.service.livelink.opentext.com", "BasicHttpBinding_DocumentManagement"), DocumentManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_DocumentManagement")
    public DocumentManagement getBasicHttpBindingDocumentManagement(WebServiceFeature... features) {
        return super.getPort(new QName("urn:DocMan.service.livelink.opentext.com", "BasicHttpBinding_DocumentManagement"), DocumentManagement.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTMANAGEMENT_EXCEPTION!= null) {
            throw DOCUMENTMANAGEMENT_EXCEPTION;
        }
        return DOCUMENTMANAGEMENT_WSDL_LOCATION;
    }

}
