
package com.opentext.livelink.service.docman;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.opentext.livelink.service.core.Attachment;
import com.opentext.livelink.service.core.ChunkedOperationContext;
import com.opentext.livelink.service.core.PageHandle;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentManagement", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
@XmlSeeAlso({
    com.opentext.ecm.api.ObjectFactory.class,
    com.opentext.livelink.service.core.ObjectFactory.class,
    com.opentext.livelink.service.docman.ObjectFactory.class
})
public interface DocumentManagement {


    /**
     * 
     * @param id
     * @param nodeRight
     */
    @WebMethod(operationName = "AddNodeRight", action = "urn:DocMan.service.livelink.opentext.com/AddNodeRight")
    @RequestWrapper(localName = "AddNodeRight", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddNodeRight")
    @ResponseWrapper(localName = "AddNodeRightResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddNodeRightResponse")
    public void addNodeRight(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "nodeRight", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        NodeRight nodeRight);

    /**
     * 
     * @param id
     * @param nodeRight
     */
    @WebMethod(operationName = "RemoveNodeRight", action = "urn:DocMan.service.livelink.opentext.com/RemoveNodeRight")
    @RequestWrapper(localName = "RemoveNodeRight", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.RemoveNodeRight")
    @ResponseWrapper(localName = "RemoveNodeRightResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.RemoveNodeRightResponse")
    public void removeNodeRight(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "nodeRight", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        NodeRight nodeRight);

    /**
     * 
     * @param id
     * @param nodeRight
     */
    @WebMethod(operationName = "UpdateNodeRight", action = "urn:DocMan.service.livelink.opentext.com/UpdateNodeRight")
    @RequestWrapper(localName = "UpdateNodeRight", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateNodeRight")
    @ResponseWrapper(localName = "UpdateNodeRightResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateNodeRightResponse")
    public void updateNodeRight(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "nodeRight", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        NodeRight nodeRight);

    /**
     * 
     * @param nodeID
     * @param operation
     * @param rights
     * @param propagation
     * @return
     *     returns com.opentext.livelink.service.core.ChunkedOperationContext
     */
    @WebMethod(operationName = "UpdateNodeRightsContext", action = "urn:DocMan.service.livelink.opentext.com/UpdateNodeRightsContext")
    @WebResult(name = "UpdateNodeRightsContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "UpdateNodeRightsContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateNodeRightsContext")
    @ResponseWrapper(localName = "UpdateNodeRightsContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateNodeRightsContextResponse")
    public ChunkedOperationContext updateNodeRightsContext(
        @WebParam(name = "nodeID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int nodeID,
        @WebParam(name = "operation", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        RightOperation operation,
        @WebParam(name = "rights", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        List<NodeRight> rights,
        @WebParam(name = "propagation", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        RightPropagation propagation);

    /**
     * 
     * @param context
     * @return
     *     returns com.opentext.livelink.service.docman.NodeRightUpdateInfo
     */
    @WebMethod(operationName = "UpdateNodeRights", action = "urn:DocMan.service.livelink.opentext.com/UpdateNodeRights")
    @WebResult(name = "UpdateNodeRightsResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "UpdateNodeRights", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateNodeRights")
    @ResponseWrapper(localName = "UpdateNodeRightsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateNodeRightsResponse")
    public NodeRightUpdateInfo updateNodeRights(
        @WebParam(name = "context", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        ChunkedOperationContext context);

    /**
     * 
     * @param parentID
     * @param name
     * @param comment
     * @param metadata
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "CreateFolder", action = "urn:DocMan.service.livelink.opentext.com/CreateFolder")
    @WebResult(name = "CreateFolderResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateFolder", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateFolder")
    @ResponseWrapper(localName = "CreateFolderResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateFolderResponse")
    public Node createFolder(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "name", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String name,
        @WebParam(name = "comment", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String comment,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata);

    /**
     * 
     * @param advancedVersionControl
     * @param parentID
     * @param attach
     * @param name
     * @param comment
     * @param metadata
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "CreateDocument", action = "urn:DocMan.service.livelink.opentext.com/CreateDocument")
    @WebResult(name = "CreateDocumentResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateDocument", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateDocument")
    @ResponseWrapper(localName = "CreateDocumentResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateDocumentResponse")
    public Node createDocument(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "name", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String name,
        @WebParam(name = "comment", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String comment,
        @WebParam(name = "advancedVersionControl", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        boolean advancedVersionControl,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata,
        @WebParam(name = "attach", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Attachment attach);

    /**
     * 
     * @param advancedVersionControl
     * @param parentID
     * @param name
     * @param comment
     * @param metadata
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateDocumentContext", action = "urn:DocMan.service.livelink.opentext.com/CreateDocumentContext")
    @WebResult(name = "CreateDocumentContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateDocumentContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateDocumentContext")
    @ResponseWrapper(localName = "CreateDocumentContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateDocumentContextResponse")
    public String createDocumentContext(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "name", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String name,
        @WebParam(name = "comment", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String comment,
        @WebParam(name = "advancedVersionControl", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        boolean advancedVersionControl,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata);

    /**
     * 
     * @param parentID
     * @param location
     * @param name
     * @param comment
     * @param metadata
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "CreateURL", action = "urn:DocMan.service.livelink.opentext.com/CreateURL")
    @WebResult(name = "CreateURLResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateURL", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateURL")
    @ResponseWrapper(localName = "CreateURLResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateURLResponse")
    public Node createURL(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "name", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String name,
        @WebParam(name = "comment", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String comment,
        @WebParam(name = "location", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String location,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata);

    /**
     * 
     * @param parentID
     * @param name
     * @param attributes
     * @param comment
     * @param metadata
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "CreateCategory", action = "urn:DocMan.service.livelink.opentext.com/CreateCategory")
    @WebResult(name = "CreateCategoryResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateCategory", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateCategory")
    @ResponseWrapper(localName = "CreateCategoryResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateCategoryResponse")
    public Node createCategory(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "name", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String name,
        @WebParam(name = "comment", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String comment,
        @WebParam(name = "attributes", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        List<Attribute> attributes,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata);

    /**
     * 
     * @param categoryID
     * @param addVersion
     * @param version
     * @return
     *     returns com.opentext.livelink.service.core.ChunkedOperationContext
     */
    @WebMethod(operationName = "UpgradeCategoryItemsContext", action = "urn:DocMan.service.livelink.opentext.com/UpgradeCategoryItemsContext")
    @WebResult(name = "UpgradeCategoryItemsContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "UpgradeCategoryItemsContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpgradeCategoryItemsContext")
    @ResponseWrapper(localName = "UpgradeCategoryItemsContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpgradeCategoryItemsContextResponse")
    public ChunkedOperationContext upgradeCategoryItemsContext(
        @WebParam(name = "categoryID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int categoryID,
        @WebParam(name = "version", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int version,
        @WebParam(name = "addVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        boolean addVersion);

    /**
     * 
     * @param context
     * @return
     *     returns com.opentext.livelink.service.docman.CategoryItemsUpgradeInfo
     */
    @WebMethod(operationName = "UpgradeCategoryItems", action = "urn:DocMan.service.livelink.opentext.com/UpgradeCategoryItems")
    @WebResult(name = "UpgradeCategoryItemsResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "UpgradeCategoryItems", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpgradeCategoryItems")
    @ResponseWrapper(localName = "UpgradeCategoryItemsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpgradeCategoryItemsResponse")
    public CategoryItemsUpgradeInfo upgradeCategoryItems(
        @WebParam(name = "context", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        ChunkedOperationContext context);

    /**
     * 
     * @param parentID
     * @param nodeType
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "GetNodeTemplate", action = "urn:DocMan.service.livelink.opentext.com/GetNodeTemplate")
    @WebResult(name = "GetNodeTemplateResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetNodeTemplate", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeTemplate")
    @ResponseWrapper(localName = "GetNodeTemplateResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeTemplateResponse")
    public Node getNodeTemplate(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "nodeType", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String nodeType);

    /**
     * 
     * @param node
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "CreateNode", action = "urn:DocMan.service.livelink.opentext.com/CreateNode")
    @WebResult(name = "CreateNodeResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateNode")
    @ResponseWrapper(localName = "CreateNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateNodeResponse")
    public Node createNode(
        @WebParam(name = "node", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Node node);

    /**
     * 
     * @param node
     * @param attach
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "CreateNodeAndVersion", action = "urn:DocMan.service.livelink.opentext.com/CreateNodeAndVersion")
    @WebResult(name = "CreateNodeAndVersionResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateNodeAndVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateNodeAndVersion")
    @ResponseWrapper(localName = "CreateNodeAndVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateNodeAndVersionResponse")
    public Node createNodeAndVersion(
        @WebParam(name = "node", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Node node,
        @WebParam(name = "attach", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Attachment attach);

    /**
     * 
     * @param node
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateNodeAndVersionContext", action = "urn:DocMan.service.livelink.opentext.com/CreateNodeAndVersionContext")
    @WebResult(name = "CreateNodeAndVersionContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateNodeAndVersionContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateNodeAndVersionContext")
    @ResponseWrapper(localName = "CreateNodeAndVersionContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateNodeAndVersionContextResponse")
    public String createNodeAndVersionContext(
        @WebParam(name = "node", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Node node);

    /**
     * 
     * @param id
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "GetNode", action = "urn:DocMan.service.livelink.opentext.com/GetNode")
    @WebResult(name = "GetNodeResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNode")
    @ResponseWrapper(localName = "GetNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeResponse")
    public Node getNode(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id);

    /**
     * 
     * @param iDs
     * @return
     *     returns java.util.List<com.opentext.livelink.service.docman.Node>
     */
    @WebMethod(operationName = "GetNodes", action = "urn:DocMan.service.livelink.opentext.com/GetNodes")
    @WebResult(name = "GetNodesResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetNodes", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodes")
    @ResponseWrapper(localName = "GetNodesResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodesResponse")
    public List<Node> getNodes(
        @WebParam(name = "IDs", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        List<Integer> iDs);

    /**
     * 
     * @param rootType
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "GetRootNode", action = "urn:DocMan.service.livelink.opentext.com/GetRootNode")
    @WebResult(name = "GetRootNodeResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetRootNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetRootNode")
    @ResponseWrapper(localName = "GetRootNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetRootNodeResponse")
    public Node getRootNode(
        @WebParam(name = "rootType", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String rootType);

    /**
     * 
     * @param parentID
     * @param name
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "GetNodeByName", action = "urn:DocMan.service.livelink.opentext.com/GetNodeByName")
    @WebResult(name = "GetNodeByNameResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetNodeByName", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeByName")
    @ResponseWrapper(localName = "GetNodeByNameResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeByNameResponse")
    public Node getNodeByName(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "name", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String name);

    /**
     * 
     * @param nickname
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "GetNodeByNickname", action = "urn:DocMan.service.livelink.opentext.com/GetNodeByNickname")
    @WebResult(name = "GetNodeByNicknameResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetNodeByNickname", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeByNickname")
    @ResponseWrapper(localName = "GetNodeByNicknameResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeByNicknameResponse")
    public Node getNodeByNickname(
        @WebParam(name = "nickname", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String nickname);

    /**
     * 
     * @param rootID
     * @param pathElements
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "GetNodeByPath", action = "urn:DocMan.service.livelink.opentext.com/GetNodeByPath")
    @WebResult(name = "GetNodeByPathResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetNodeByPath", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeByPath")
    @ResponseWrapper(localName = "GetNodeByPathResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeByPathResponse")
    public Node getNodeByPath(
        @WebParam(name = "rootID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int rootID,
        @WebParam(name = "pathElements", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        List<String> pathElements);

    /**
     * 
     * @param type
     * @param key
     * @return
     *     returns com.opentext.livelink.service.docman.AttributeGroup
     */
    @WebMethod(operationName = "GetAttributeGroupTemplate", action = "urn:DocMan.service.livelink.opentext.com/GetAttributeGroupTemplate")
    @WebResult(name = "GetAttributeGroupTemplateResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetAttributeGroupTemplate", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetAttributeGroupTemplate")
    @ResponseWrapper(localName = "GetAttributeGroupTemplateResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetAttributeGroupTemplateResponse")
    public AttributeGroup getAttributeGroupTemplate(
        @WebParam(name = "type", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String type,
        @WebParam(name = "key", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String key);

    /**
     * 
     * @param type
     * @param key
     * @return
     *     returns com.opentext.livelink.service.docman.AttributeGroupDefinition
     */
    @WebMethod(operationName = "GetAttributeGroupDefinition", action = "urn:DocMan.service.livelink.opentext.com/GetAttributeGroupDefinition")
    @WebResult(name = "GetAttributeGroupDefinitionResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetAttributeGroupDefinition", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetAttributeGroupDefinition")
    @ResponseWrapper(localName = "GetAttributeGroupDefinitionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetAttributeGroupDefinitionResponse")
    public AttributeGroupDefinition getAttributeGroupDefinition(
        @WebParam(name = "type", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String type,
        @WebParam(name = "key", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String key);

    /**
     * 
     * @param categoryID
     * @return
     *     returns com.opentext.livelink.service.docman.AttributeGroupDefinition
     */
    @WebMethod(operationName = "GetCategoryDefinition", action = "urn:DocMan.service.livelink.opentext.com/GetCategoryDefinition")
    @WebResult(name = "GetCategoryDefinitionResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetCategoryDefinition", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetCategoryDefinition")
    @ResponseWrapper(localName = "GetCategoryDefinitionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetCategoryDefinitionResponse")
    public AttributeGroupDefinition getCategoryDefinition(
        @WebParam(name = "categoryID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int categoryID);

    /**
     * 
     * @param categoryID
     * @return
     *     returns com.opentext.livelink.service.docman.AttributeGroup
     */
    @WebMethod(operationName = "GetCategoryTemplate", action = "urn:DocMan.service.livelink.opentext.com/GetCategoryTemplate")
    @WebResult(name = "GetCategoryTemplateResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetCategoryTemplate", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetCategoryTemplate")
    @ResponseWrapper(localName = "GetCategoryTemplateResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetCategoryTemplateResponse")
    public AttributeGroup getCategoryTemplate(
        @WebParam(name = "categoryID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int categoryID);

    /**
     * 
     * @param nodeID
     * @param versionNum
     * @return
     *     returns java.util.List<com.opentext.livelink.service.docman.Version>
     */
    @WebMethod(operationName = "ListRenditions", action = "urn:DocMan.service.livelink.opentext.com/ListRenditions")
    @WebResult(name = "ListRenditionsResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "ListRenditions", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListRenditions")
    @ResponseWrapper(localName = "ListRenditionsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListRenditionsResponse")
    public List<Version> listRenditions(
        @WebParam(name = "nodeID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int nodeID,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum);

    /**
     * 
     * @param nodeID
     * @param attach
     * @param renditionType
     * @param versionNum
     * @return
     *     returns com.opentext.livelink.service.docman.Version
     */
    @WebMethod(operationName = "CreateRendition", action = "urn:DocMan.service.livelink.opentext.com/CreateRendition")
    @WebResult(name = "CreateRenditionResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateRendition", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateRendition")
    @ResponseWrapper(localName = "CreateRenditionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateRenditionResponse")
    public Version createRendition(
        @WebParam(name = "nodeID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int nodeID,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum,
        @WebParam(name = "renditionType", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String renditionType,
        @WebParam(name = "attach", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Attachment attach);

    /**
     * 
     * @param nodeID
     * @param renditionType
     * @param versionNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateRenditionContext", action = "urn:DocMan.service.livelink.opentext.com/CreateRenditionContext")
    @WebResult(name = "CreateRenditionContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateRenditionContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateRenditionContext")
    @ResponseWrapper(localName = "CreateRenditionContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateRenditionContextResponse")
    public String createRenditionContext(
        @WebParam(name = "nodeID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int nodeID,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum,
        @WebParam(name = "renditionType", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String renditionType);

    /**
     * 
     * @param nodeID
     * @param renditionType
     * @param versionNum
     */
    @WebMethod(operationName = "DeleteRendition", action = "urn:DocMan.service.livelink.opentext.com/DeleteRendition")
    @RequestWrapper(localName = "DeleteRendition", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.DeleteRendition")
    @ResponseWrapper(localName = "DeleteRenditionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.DeleteRenditionResponse")
    public void deleteRendition(
        @WebParam(name = "nodeID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int nodeID,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum,
        @WebParam(name = "renditionType", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String renditionType);

    /**
     * 
     * @param nodeID
     * @param renditionType
     * @param versionNum
     * @return
     *     returns com.opentext.livelink.service.core.Attachment
     */
    @WebMethod(operationName = "GetRenditionContents", action = "urn:DocMan.service.livelink.opentext.com/GetRenditionContents")
    @WebResult(name = "GetRenditionContentsResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetRenditionContents", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetRenditionContents")
    @ResponseWrapper(localName = "GetRenditionContentsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetRenditionContentsResponse")
    public Attachment getRenditionContents(
        @WebParam(name = "nodeID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int nodeID,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum,
        @WebParam(name = "renditionType", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String renditionType);

    /**
     * 
     * @param nodeID
     * @param renditionType
     * @param versionNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRenditionContentsContext", action = "urn:DocMan.service.livelink.opentext.com/GetRenditionContentsContext")
    @WebResult(name = "GetRenditionContentsContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetRenditionContentsContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetRenditionContentsContext")
    @ResponseWrapper(localName = "GetRenditionContentsContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetRenditionContentsContextResponse")
    public String getRenditionContentsContext(
        @WebParam(name = "nodeID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int nodeID,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum,
        @WebParam(name = "renditionType", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String renditionType);

    /**
     * 
     * @param node
     */
    @WebMethod(operationName = "UpdateNode", action = "urn:DocMan.service.livelink.opentext.com/UpdateNode")
    @RequestWrapper(localName = "UpdateNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateNode")
    @ResponseWrapper(localName = "UpdateNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateNodeResponse")
    public void updateNode(
        @WebParam(name = "node", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Node node);

    /**
     * 
     * @param categoryID
     * @param attributes
     * @return
     *     returns com.opentext.livelink.service.docman.AttributeGroupDefinition
     */
    @WebMethod(operationName = "UpdateCategory", action = "urn:DocMan.service.livelink.opentext.com/UpdateCategory")
    @WebResult(name = "UpdateCategoryResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "UpdateCategory", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateCategory")
    @ResponseWrapper(localName = "UpdateCategoryResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateCategoryResponse")
    public AttributeGroupDefinition updateCategory(
        @WebParam(name = "categoryID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int categoryID,
        @WebParam(name = "attributes", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        List<Attribute> attributes);

    /**
     * 
     * @param id
     * @param newName
     */
    @WebMethod(operationName = "RenameNode", action = "urn:DocMan.service.livelink.opentext.com/RenameNode")
    @RequestWrapper(localName = "RenameNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.RenameNode")
    @ResponseWrapper(localName = "RenameNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.RenameNodeResponse")
    public void renameNode(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "newName", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String newName);

    /**
     * 
     * @param position
     * @param id
     */
    @WebMethod(operationName = "RepositionNode", action = "urn:DocMan.service.livelink.opentext.com/RepositionNode")
    @RequestWrapper(localName = "RepositionNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.RepositionNode")
    @ResponseWrapper(localName = "RepositionNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.RepositionNodeResponse")
    public void repositionNode(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "position", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int position);

    /**
     * 
     * @param id
     * @param positions
     */
    @WebMethod(operationName = "RearrangeNodes", action = "urn:DocMan.service.livelink.opentext.com/RearrangeNodes")
    @RequestWrapper(localName = "RearrangeNodes", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.RearrangeNodes")
    @ResponseWrapper(localName = "RearrangeNodesResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.RearrangeNodesResponse")
    public void rearrangeNodes(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "positions", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        List<NodePosition> positions);

    /**
     * 
     * @param id
     * @param userID
     */
    @WebMethod(operationName = "ReserveNode", action = "urn:DocMan.service.livelink.opentext.com/ReserveNode")
    @RequestWrapper(localName = "ReserveNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ReserveNode")
    @ResponseWrapper(localName = "ReserveNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ReserveNodeResponse")
    public void reserveNode(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "userID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Integer userID);

    /**
     * 
     * @param id
     */
    @WebMethod(operationName = "UnreserveNode", action = "urn:DocMan.service.livelink.opentext.com/UnreserveNode")
    @RequestWrapper(localName = "UnreserveNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UnreserveNode")
    @ResponseWrapper(localName = "UnreserveNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UnreserveNodeResponse")
    public void unreserveNode(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id);

    /**
     * 
     * @param id
     * @param versionNum
     * @return
     *     returns com.opentext.livelink.service.docman.Version
     */
    @WebMethod(operationName = "GetVersion", action = "urn:DocMan.service.livelink.opentext.com/GetVersion")
    @WebResult(name = "GetVersionResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetVersionResponse")
    public Version getVersion(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum);

    /**
     * 
     * @param id
     * @param versionNum
     * @return
     *     returns com.opentext.livelink.service.core.Attachment
     */
    @WebMethod(operationName = "GetVersionContents", action = "urn:DocMan.service.livelink.opentext.com/GetVersionContents")
    @WebResult(name = "GetVersionContentsResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetVersionContents", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetVersionContents")
    @ResponseWrapper(localName = "GetVersionContentsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetVersionContentsResponse")
    public Attachment getVersionContents(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum);

    /**
     * 
     * @param id
     * @param versionNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersionContentsContext", action = "urn:DocMan.service.livelink.opentext.com/GetVersionContentsContext")
    @WebResult(name = "GetVersionContentsContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetVersionContentsContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetVersionContentsContext")
    @ResponseWrapper(localName = "GetVersionContentsContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetVersionContentsContextResponse")
    public String getVersionContentsContext(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum);

    /**
     * 
     * @param id
     * @param attach
     * @param metadata
     * @return
     *     returns com.opentext.livelink.service.docman.Version
     */
    @WebMethod(operationName = "AddVersion", action = "urn:DocMan.service.livelink.opentext.com/AddVersion")
    @WebResult(name = "AddVersionResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "AddVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddVersion")
    @ResponseWrapper(localName = "AddVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddVersionResponse")
    public Version addVersion(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata,
        @WebParam(name = "attach", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Attachment attach);

    /**
     * 
     * @param id
     * @param metadata
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddVersionContext", action = "urn:DocMan.service.livelink.opentext.com/AddVersionContext")
    @WebResult(name = "AddVersionContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "AddVersionContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddVersionContext")
    @ResponseWrapper(localName = "AddVersionContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddVersionContextResponse")
    public String addVersionContext(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata);

    /**
     * 
     * @param id
     * @param attach
     * @param metadata
     * @return
     *     returns com.opentext.livelink.service.docman.Version
     */
    @WebMethod(operationName = "AddMajorVersion", action = "urn:DocMan.service.livelink.opentext.com/AddMajorVersion")
    @WebResult(name = "AddMajorVersionResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "AddMajorVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddMajorVersion")
    @ResponseWrapper(localName = "AddMajorVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddMajorVersionResponse")
    public Version addMajorVersion(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata,
        @WebParam(name = "attach", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Attachment attach);

    /**
     * 
     * @param id
     * @param metadata
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddMajorVersionContext", action = "urn:DocMan.service.livelink.opentext.com/AddMajorVersionContext")
    @WebResult(name = "AddMajorVersionContextResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "AddMajorVersionContext", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddMajorVersionContext")
    @ResponseWrapper(localName = "AddMajorVersionContextResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.AddMajorVersionContextResponse")
    public String addMajorVersionContext(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata);

    /**
     * 
     * @param id
     * @param numberToKeep
     */
    @WebMethod(operationName = "PurgeVersions", action = "urn:DocMan.service.livelink.opentext.com/PurgeVersions")
    @RequestWrapper(localName = "PurgeVersions", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.PurgeVersions")
    @ResponseWrapper(localName = "PurgeVersionsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.PurgeVersionsResponse")
    public void purgeVersions(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "numberToKeep", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int numberToKeep);

    /**
     * 
     * @param id
     * @param metadata
     * @param versionNum
     * @return
     *     returns com.opentext.livelink.service.docman.Version
     */
    @WebMethod(operationName = "PromoteVersion", action = "urn:DocMan.service.livelink.opentext.com/PromoteVersion")
    @WebResult(name = "PromoteVersionResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "PromoteVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.PromoteVersion")
    @ResponseWrapper(localName = "PromoteVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.PromoteVersionResponse")
    public Version promoteVersion(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum,
        @WebParam(name = "metadata", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Metadata metadata);

    /**
     * 
     * @param parentID
     * @param partialData
     * @return
     *     returns java.util.List<com.opentext.livelink.service.docman.Node>
     */
    @WebMethod(operationName = "ListNodes", action = "urn:DocMan.service.livelink.opentext.com/ListNodes")
    @WebResult(name = "ListNodesResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "ListNodes", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListNodes")
    @ResponseWrapper(localName = "ListNodesResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListNodesResponse")
    public List<Node> listNodes(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "partialData", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        boolean partialData);

    /**
     * 
     * @param parentID
     * @param pageSpec
     * @return
     *     returns com.opentext.livelink.service.docman.NodePageResult
     */
    @WebMethod(operationName = "ListNodesByPage", action = "urn:DocMan.service.livelink.opentext.com/ListNodesByPage")
    @WebResult(name = "ListNodesByPageResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "ListNodesByPage", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListNodesByPage")
    @ResponseWrapper(localName = "ListNodesByPageResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListNodesByPageResponse")
    public NodePageResult listNodesByPage(
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "pageSpec", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        NodePageSpecification pageSpec);

    /**
     * 
     * @param id
     * @return
     *     returns java.util.List<com.opentext.livelink.service.docman.Node>
     */
    @WebMethod(operationName = "ListReferences", action = "urn:DocMan.service.livelink.opentext.com/ListReferences")
    @WebResult(name = "ListReferencesResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "ListReferences", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListReferences")
    @ResponseWrapper(localName = "ListReferencesResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListReferencesResponse")
    public List<Node> listReferences(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id);

    /**
     * 
     * @param id
     * @param copyOptions
     * @param parentID
     * @param newName
     * @return
     *     returns com.opentext.livelink.service.docman.Node
     */
    @WebMethod(operationName = "CopyNode", action = "urn:DocMan.service.livelink.opentext.com/CopyNode")
    @WebResult(name = "CopyNodeResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CopyNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CopyNode")
    @ResponseWrapper(localName = "CopyNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CopyNodeResponse")
    public Node copyNode(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "newName", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String newName,
        @WebParam(name = "copyOptions", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        CopyOptions copyOptions);

    /**
     * 
     * @param id
     */
    @WebMethod(operationName = "DeleteNode", action = "urn:DocMan.service.livelink.opentext.com/DeleteNode")
    @RequestWrapper(localName = "DeleteNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.DeleteNode")
    @ResponseWrapper(localName = "DeleteNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.DeleteNodeResponse")
    public void deleteNode(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id);

    /**
     * 
     * @param id
     * @param moveOptions
     * @param parentID
     * @param newName
     */
    @WebMethod(operationName = "MoveNode", action = "urn:DocMan.service.livelink.opentext.com/MoveNode")
    @RequestWrapper(localName = "MoveNode", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.MoveNode")
    @ResponseWrapper(localName = "MoveNodeResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.MoveNodeResponse")
    public void moveNode(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "parentID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int parentID,
        @WebParam(name = "newName", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String newName,
        @WebParam(name = "moveOptions", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        MoveOptions moveOptions);

    /**
     * 
     * @param version
     */
    @WebMethod(operationName = "UpdateVersion", action = "urn:DocMan.service.livelink.opentext.com/UpdateVersion")
    @RequestWrapper(localName = "UpdateVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateVersion")
    @ResponseWrapper(localName = "UpdateVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UpdateVersionResponse")
    public void updateVersion(
        @WebParam(name = "version", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        Version version);

    /**
     * 
     * @param id
     * @param versionNum
     */
    @WebMethod(operationName = "DeleteVersion", action = "urn:DocMan.service.livelink.opentext.com/DeleteVersion")
    @RequestWrapper(localName = "DeleteVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.DeleteVersion")
    @ResponseWrapper(localName = "DeleteVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.DeleteVersionResponse")
    public void deleteVersion(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum);

    /**
     * 
     * @param id
     * @param versionNum
     */
    @WebMethod(operationName = "LockVersion", action = "urn:DocMan.service.livelink.opentext.com/LockVersion")
    @RequestWrapper(localName = "LockVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.LockVersion")
    @ResponseWrapper(localName = "LockVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.LockVersionResponse")
    public void lockVersion(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum);

    /**
     * 
     * @param id
     * @param versionNum
     */
    @WebMethod(operationName = "UnlockVersion", action = "urn:DocMan.service.livelink.opentext.com/UnlockVersion")
    @RequestWrapper(localName = "UnlockVersion", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UnlockVersion")
    @ResponseWrapper(localName = "UnlockVersionResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UnlockVersionResponse")
    public void unlockVersion(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "versionNum", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int versionNum);

    /**
     * 
     * @param id
     * @param releaseName
     * @param major
     * @return
     *     returns com.opentext.livelink.service.docman.CompoundDocRelease
     */
    @WebMethod(operationName = "CreateRelease", action = "urn:DocMan.service.livelink.opentext.com/CreateRelease")
    @WebResult(name = "CreateReleaseResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "CreateRelease", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateRelease")
    @ResponseWrapper(localName = "CreateReleaseResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.CreateReleaseResponse")
    public CompoundDocRelease createRelease(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "major", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        boolean major,
        @WebParam(name = "releaseName", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        String releaseName);

    /**
     * 
     * @param id
     * @return
     *     returns java.util.List<com.opentext.livelink.service.docman.CompoundDocRelease>
     */
    @WebMethod(operationName = "ListReleases", action = "urn:DocMan.service.livelink.opentext.com/ListReleases")
    @WebResult(name = "ListReleasesResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "ListReleases", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListReleases")
    @ResponseWrapper(localName = "ListReleasesResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.ListReleasesResponse")
    public List<CompoundDocRelease> listReleases(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id);

    /**
     * 
     * @param id
     * @param minor
     * @param major
     * @return
     *     returns com.opentext.livelink.service.docman.CompoundDocRelease
     */
    @WebMethod(operationName = "GetRelease", action = "urn:DocMan.service.livelink.opentext.com/GetRelease")
    @WebResult(name = "GetReleaseResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetRelease", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetRelease")
    @ResponseWrapper(localName = "GetReleaseResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetReleaseResponse")
    public CompoundDocRelease getRelease(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "major", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int major,
        @WebParam(name = "minor", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int minor);

    /**
     * 
     * @param id
     * @param minor
     * @param major
     */
    @WebMethod(operationName = "DeleteRelease", action = "urn:DocMan.service.livelink.opentext.com/DeleteRelease")
    @RequestWrapper(localName = "DeleteRelease", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.DeleteRelease")
    @ResponseWrapper(localName = "DeleteReleaseResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.DeleteReleaseResponse")
    public void deleteRelease(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "major", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int major,
        @WebParam(name = "minor", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int minor);

    /**
     * 
     * @param id
     * @param minor
     * @param major
     */
    @WebMethod(operationName = "LockRelease", action = "urn:DocMan.service.livelink.opentext.com/LockRelease")
    @RequestWrapper(localName = "LockRelease", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.LockRelease")
    @ResponseWrapper(localName = "LockReleaseResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.LockReleaseResponse")
    public void lockRelease(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "major", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int major,
        @WebParam(name = "minor", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int minor);

    /**
     * 
     * @param id
     * @param minor
     * @param major
     */
    @WebMethod(operationName = "UnlockRelease", action = "urn:DocMan.service.livelink.opentext.com/UnlockRelease")
    @RequestWrapper(localName = "UnlockRelease", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UnlockRelease")
    @ResponseWrapper(localName = "UnlockReleaseResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.UnlockReleaseResponse")
    public void unlockRelease(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "major", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int major,
        @WebParam(name = "minor", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int minor);

    /**
     * 
     * @param id
     * @return
     *     returns java.util.List<com.opentext.livelink.service.docman.NodeAuditRecord>
     */
    @WebMethod(operationName = "GetNodeAuditRecords", action = "urn:DocMan.service.livelink.opentext.com/GetNodeAuditRecords")
    @WebResult(name = "GetNodeAuditRecordsResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetNodeAuditRecords", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeAuditRecords")
    @ResponseWrapper(localName = "GetNodeAuditRecordsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeAuditRecordsResponse")
    public List<NodeAuditRecord> getNodeAuditRecords(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id);

    /**
     * 
     * @param id
     * @param pageHandle
     * @return
     *     returns com.opentext.livelink.service.docman.PagedNodeAuditData
     */
    @WebMethod(operationName = "GetPagedNodeAuditData", action = "urn:DocMan.service.livelink.opentext.com/GetPagedNodeAuditData")
    @WebResult(name = "GetPagedNodeAuditDataResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetPagedNodeAuditData", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetPagedNodeAuditData")
    @ResponseWrapper(localName = "GetPagedNodeAuditDataResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetPagedNodeAuditDataResponse")
    public PagedNodeAuditData getPagedNodeAuditData(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "pageHandle", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        PageHandle pageHandle);

    /**
     * 
     * @param id
     * @return
     *     returns com.opentext.livelink.service.docman.NodeRights
     */
    @WebMethod(operationName = "GetNodeRights", action = "urn:DocMan.service.livelink.opentext.com/GetNodeRights")
    @WebResult(name = "GetNodeRightsResult", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
    @RequestWrapper(localName = "GetNodeRights", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeRights")
    @ResponseWrapper(localName = "GetNodeRightsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.GetNodeRightsResponse")
    public NodeRights getNodeRights(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id);

    /**
     * 
     * @param id
     * @param rights
     */
    @WebMethod(operationName = "SetNodeRights", action = "urn:DocMan.service.livelink.opentext.com/SetNodeRights")
    @RequestWrapper(localName = "SetNodeRights", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.SetNodeRights")
    @ResponseWrapper(localName = "SetNodeRightsResponse", targetNamespace = "urn:DocMan.service.livelink.opentext.com", className = "com.opentext.livelink.service.docman.SetNodeRightsResponse")
    public void setNodeRights(
        @WebParam(name = "ID", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        int id,
        @WebParam(name = "rights", targetNamespace = "urn:DocMan.service.livelink.opentext.com")
        NodeRights rights);

}
