
package com.opentext.livelink.service.searchservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b05 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchService", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", wsdlLocation = "http://sd1kappuy11:8080/les-services/services/SearchService?wsdl")
public class SearchService_Service
    extends Service
{

    private final static URL SEARCHSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHSERVICE_EXCEPTION;
    private final static QName SEARCHSERVICE_QNAME = new QName("urn:SearchServices.service.livelink.opentext.com", "SearchService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sd1kappuy11:8080/les-services/services/SearchService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHSERVICE_WSDL_LOCATION = url;
        SEARCHSERVICE_EXCEPTION = e;
    }

    public SearchService_Service() {
        super(__getWsdlLocation(), SEARCHSERVICE_QNAME);
    }

    public SearchService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHSERVICE_QNAME, features);
    }

    public SearchService_Service(URL wsdlLocation) {
        super(wsdlLocation, SEARCHSERVICE_QNAME);
    }

    public SearchService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHSERVICE_QNAME, features);
    }

    public SearchService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "BasicHttpBinding_SearchService")
    public SearchService getBasicHttpBindingSearchService() {
        return super.getPort(new QName("urn:SearchServices.service.livelink.opentext.com", "BasicHttpBinding_SearchService"), SearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchService
     */
    @WebEndpoint(name = "BasicHttpBinding_SearchService")
    public SearchService getBasicHttpBindingSearchService(WebServiceFeature... features) {
        return super.getPort(new QName("urn:SearchServices.service.livelink.opentext.com", "BasicHttpBinding_SearchService"), SearchService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHSERVICE_EXCEPTION!= null) {
            throw SEARCHSERVICE_EXCEPTION;
        }
        return SEARCHSERVICE_WSDL_LOCATION;
    }

}
